identidock:
  image: vlad75/identidock:1.0 
  ports:
   - "5000:5000"
  environment:
    ENV: DEV 
  links:
    - dnmonster
    - redis

dnmonster:
  image: amouat/dnmonster:1.0

redis:
  image: redis:3.0
